### ISSUE TITLE
Questions about the formulas mentioned in the paper

### ISSUE THREAD

**Issue by Alax1548** [FanZhichen/NCD-IIC#1]
![1708602379140](https://github.com/FanZhichen/NCD-IIC/assets/111670659/5931978b-88ea-45ac-b32c-685d917189f6)
Hello author, I have a question after reading your paper. The function of the formula in the figure stated in the paper is to enlarge the difference between labeled data and unlabeled data so that they can be separated, but shouldn't the formula make the output of labeled data and unlabeled data more similar after minimizing the loss function?

**Comment by FanZhichen** [comment]
Thanks for your question.
Firstly, in the setting of NCD problem, it has been mentioned that labelled and unlabelled data should be semantically similar. This assumption forms the basis of some early two-staged methods, such as KCL and MCL, which learn pairwise similarity functions on labelled data and then apply them to unlabelled data.
Secondly, after 2021, single-staged methods handle both labelled and unlabelled data simultaneously, implicitly assuming this similarity between them. Therefore, single-staged methods focus more on how to distinguish different classes in the embedding space. It can be said that the current methods are more closely related to unsupervised learning and self-supervised learning.
